### PR TITLE
Typo Fixed

### PR DESCRIPTION
**Pull request by sudhanshu-77**
namespaces is > namespaces are

### CODE REVIEW

**Comment by sudhanshu-77** [comment]
Hi 👋, Please review the changes and merge. Thanks

**Comment by oswalpalash** [comment]
What is store xss?

**Comment by oswalpalash** [comment]
Please - 
1. Stop changing the data that comes in directly from automated feeds. 
2. Understand the context of the data that you're changing. 

Are the changes for hacktoberfest?

**Comment by sudhanshu-77** [comment]
> Please -
> 
> 1. Stop changing the data that comes in directly from automated feeds.
> 2. Understand the context of the data that you're changing.
> 
> Are the changes for hacktoberfest?

I am sorry, I'm new in open source ,From next time I will remember above mentions points. Please ignore

**Comment by sudhanshu-77** [comment]
> namespaces is > namespaces are

is this valid or not ?

**Comment by joshbressers** [comment]
Hi @sudhanshu-77 

We can't accept this PR. A json file is being deleted

The typo fixes could be accepted, but are quite trivial. I think if you want to get involved there are more substantial things to investigate. I would suggest joining the Slack
https://gsd.id/quick-links

**Pull request closed without merging**
