### PR TITLE
Update README.md - fix grammatrical errors in README.

### PR DESCRIPTION
**Pull request by ayushrakesh**
I have noticed some grammatical mistakes in **README** inside section "**Global Security Database (GSD)**"

"**Due to these problems we**"  should be "**Due to these problems, we**"

" **create their own bespoke**"  should be " **create its own bespoke**"

Screenshot-

Screenshot (141)

### CODE REVIEW

**Comment by ayushrakesh** [comment]
Please review my PR.

**Comment by oswalpalash** [comment]
Is this for hacktoberfest?

**Comment by ayushrakesh** [comment]
No.

**Comment by ayushrakesh** [comment]
for hacksquad .

**Pull request closed without merging**
