### PR TITLE
Updates for linux vendors

### PR DESCRIPTION
**Pull request by kurtseifried**

### CODE REVIEW

**Comment by kurtseifried** [comment]
@athix as per request

**Comment by athix** [comment]
I wonder if it would be wise to long term simply supply websites that augment IDs as some sort of meta layer thing, instead of embedding it directly into the references for every CVE in existence...

Pros and cons to both methods I suppose, and with OSV we can at least clearly label these types of references in the future.

**Review by athix — APPROVED** [review]
It might be wise to wait on merging this until we fix everything to use OSV and follow an explicit GSD schema. Then you won't have to re-parse this potentially.

**Comment by joshbressers** [comment]
I'm OK merging this now. When it's time to parse things we already have to verify a ton of stuff. I'm a fan of capturing all this now and fixing it up soon

**Comment by athix** [comment]
Agreed. I'm working on adding a schema to validate against, which should ideally make this a lot easier and provide us something to use for GitHub action validations of the data. It will obviously use OSV, but will have other things defined such as the namespaces that are GSD specific.

**Pull request merged**
